# Generated by Django 3.2.4 on 2021-06-22 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut')),
                ('pnombre', models.CharField(max_length=30, verbose_name='Primer nombre')),
                ('apaterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('amaterno', models.CharField(max_length=30, null=True, verbose_name='Apellido Materno')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(blank=True, max_length=30, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rayoapp.cliente')),
            ],
        ),
    ]
